// Generated by XenoTemplateTool v1.2 on 2018/3/23 at 22:53
using UnityEditor;
namespace CYM.Utile
{


    public static class ExtendedTemplateMenuItems
    {

        [MenuItem("Assets/ScriptTemplates/AutoMono", false, 0)]
        public static void AutoMono()
        {
            XenoTemplateTool.PromptUserForNameAuto();
        }
    }

}